apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "psql.fullname" . }}
  namespace: {{ .Values.psql.projectNamespace | quote }}
spec:
  backoffLimit: {{ .Values.psql.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.psql.job.ttlSecondsAfterFinished }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.psql.job.container.image.repository }}:{{ .Values.psql.job.container.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.psql.job.container.image.pullPolicy  }}
          command: {{ .Values.psql.job.container.command }}
          envFrom:
            - secretRef:
                name: {{ .Values.psql.job.container.envVarsSecret }}
            - secretRef:
                name: {{ .Values.psql.job.container.extraEnvVarsSecret }}
          volumeMounts:
            - name: {{ .Values.psql.job.container.volumeName }}
              mountPath: {{ .Values.psql.job.container.mountPath }}
          resources:
            {{- toYaml .Values.psql.job.container.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.psql.job.container.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.psql.pvc.name }}
      restartPolicy: {{ .Values.psql.job.container.restartPolicy }}
