apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "psql.fullname" . }}
  namespace: {{ .Values.psql.projectNamespace | quote }}
spec:
  backoffLimit: {{ .Values.psql.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.psql.job.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.psql.job.activeDeadlineSeconds }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.psql.job.container.image.repository }}:{{ .Values.psql.job.container.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.psql.job.container.image.pullPolicy  }}
          command: [{{ .Values.psql.job.container.command }}]
          env:
            - name: JENKINS_BUILD_ID
              value: {{ .Values.psql.jenkinsBuildId | quote }}
            - name: JENKINS_START_BUILD_DATE_TIME
              value: {{ .Values.psql.jenkinsStartBuildDateTime| quote }}
            - name: JENKINS_START_BUILD_USERNAME
              value: {{ .Values.psql.jenkinsStartBuildUserName | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.psql.job.container.envVarsSecret }}
            - secretRef:
                name: {{ .Values.psql.job.container.extraEnvVarsSecret }}
          volumeMounts:
            - name: {{ .Values.psql.job.container.volumeName }}
              mountPath: {{ .Values.psql.job.container.mountPath }}
          resources:
            {{- toYaml .Values.psql.job.container.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.psql.job.container.volumeName }}
          persistentVolumeClaim:
            claimName: {{ template "psql.pvc.uniqueName" . }}
      restartPolicy: {{ .Values.psql.job.container.restartPolicy }}
