apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.psql.pvc.name }}
  namespace: {{ .Values.psql.projectNamespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.psql.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.psql.pvc.storageSize }}