psqlDump:
  projectNamespace: "unam"
  job:
    image: "bblayhub/pg-dump-restore-aws-cli:1.3"
    extraEnvVarsSecret: "db-backup-secret"
    volumeName: "db-backup-data"
    mountPath: "/mnt/ebs-volume"
    restartPolicy: "Never"
    backoffLimit: "4"
    command: "['/bin/bash', '/pg_dump_restore.sh']"
  pvc:
    name: "db-backup-volume"
    storageClassName: "gp2"
    storageSize: "1Gi"
