psql:
  projectNamespace: ""
  job:
    image:
      repository: "org/folio/psql-dump-helm"
      pullPolicy: Always
      tag: ""
    EnvVarsSecret: "s3-postgres-backups-credentials"
    volumeName: "db-backup-data"
    mountPath: "/mnt/ebs-volume"
    restartPolicy: "Never"
    backoffLimit: "3"
    command: "['/bin/bash', '/pg_dump_restore.sh']"
    nameOverride: ""
    fullnameOverride: ""
  pvc:
    name: "db-backup-volume"
    storageClassName: "gp2"
    storageSize: "1Gi"
