psql:
  jenkinsBuildId: "1"
  jenkinsStartBuildDateTime: ""
  jenkinsStartBuildUserName: ""
  projectNamespace: ""
  job:
    backoffLimit: "0"
    ttlSecondsAfterFinished: "10"
    activeDeadlineSeconds: "1800"
    container:
      image:
        repository: "docker-folio.dev.folio.org/org/folio/psql-dump-helm"
        pullPolicy: Always
        tag: "${chartVersion}"
      # The below secret provided with every project deployment and has value of cluster/project name,
      # aws s3 bucket name, aws s3 access and secret keys
      envVarsSecret: "aws-postgres-backups-s3-bucket-credentials"
      # The below secret provided with every project deployment and give us pg_username,
      # pg_password, pg_db_name, pg_db_host_name values
      extraEnvVarsSecret: "db-connect-modules"
      volumeName: "psql-backup-data"
      mountPath: "/mnt/ebs-volume"
      restartPolicy: "Never"
      command: "'/bin/bash', '/pg_dump_restore.sh'"
      resources:
        limits:
          cpu: "800m"
          memory: "250Mi"
        requests:
          cpu: "500m"
          memory: "150Mi"
  pvc:
    name: "psql-backup-volume"
    storageClassName: "gp2"
    storageSize: "8Gi"

nameOverride: ""
fullnameOverride: ""