psqlDump:
  projectNamespace: ""
  job:
    image: ""
    imagePullPolicy: "Always"
    extraEnvVarsSecret: ""
    volumeName: "db-backup-data"
    mountPath: "/mnt/ebs-volume"
    restartPolicy: "Never"
    backoffLimit: "3"
    command: "['/bin/bash', '/pg_dump_restore.sh']"
  pvc:
    name: "db-backup-volume"
    storageClassName: "gp2"
    storageSize: "1Gi"
