psql:
  jenkinsBuildId: "1"
  jenkinsStartBuildDateTime: ""
  jenkinsStartBuildUserName: ""
  projectNamespace: ""
  job:
    backoffLimit: "0"
    ttlSecondsAfterFinished: "10"
    activeDeadlineSeconds: "1200"
    container:
      image:
        repository: "docker-folio.dev.folio.org/org/folio/psql-dump-helm"
        pullPolicy: Always
        tag: ""
      envVarsSecret: "s3-postgres-backups-credentials"
      extraEnvVarsSecret: "db-connect-modules"
      volumeName: "psql-backup-data"
      mountPath: "/mnt/ebs-volume"
      restartPolicy: "Never"
      command: "'sleep', '300'"
      resources:
        limits:
          cpu: "800m"
          memory: "250Mi"
        requests:
          cpu: "500m"
          memory: "150Mi"
  pvc:
    name: "psql-backup-volume"
    storageClassName: "gp2"
    storageSize: "1Gi"

nameOverride: ""
fullnameOverride: ""