psql:
  projectNamespace: ""
  job:
    backoffLimit: "0"
    ttlSecondsAfterFinished: "120"
    container:
      image:
        repository: "docker.dev.folio.org/org/folio/psql-dump-helm"
        pullPolicy: Always
        tag: ""
      envVarsSecret: "s3-postgres-backups-credentials"
      extraEnvVarsSecret: "db-connect-modules"
      volumeName: "db-backup-data"
      mountPath: "/mnt/ebs-volume"
      restartPolicy: "Never"
      command: "['/bin/bash', '/pg_dump_restore.sh']"
      resources:
        limits:
          cpu: "800m"
          memory: "250Mi"
        requests:
          cpu: "500m"
          memory: "150Mi"
  pvc:
    name: "db-backup-volume"
    storageClassName: "gp2"
    storageSize: "1Gi"

nameOverride: ""
fullnameOverride: ""